### ISSUE TITLE
getGoogleAuth is not a valid API name.

### ISSUE THREAD

**Issue by pankaj-andhale-brainlabsdigital-com** [google-marketing-solutions/gps-phoebe#7]
![image](https://github.com/google-marketing-solutions/gps-phoebe/assets/137157861/5c5b5182-9e96-4707-ac43-a113225987ea)

when tried to test the prediction variable Snadboxed JS gave this error,
**getGoogleAuth is not a valid API name.**

**Comment by tdsymonds** [comment]
Unfortunately, the API release has been delayed, so the code has been reverted and will be re-released when it has launched.

Stay tuned for the v2.0.0 launch.

**Comment by tdsymonds** [comment]
The API has now fully launched, [see docs](https://developers.google.com/tag-platform/tag-manager/server-side/api#getgoogleauth). So this should now work for you.

Any issues, please reopen and provide more information.

Thanks
